name: Build and send to QA stageQa

on:
  pull_request:
    types:
      - closed
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  send_to_qa_stage:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with: { java-version: 1.17 }

      - name: Get pull request details
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_TITLE=$(gh pr view ${{ github.event.pull_request.number }} --json title --jq '.title')
          PR_AUTHOR=$(gh pr view ${{ github.event.pull_request.number }} --json author --jq '.author.name')
          PR_URL=$(gh pr view ${{ github.event.pull_request.number }} --json url --jq '.url')
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
          echo "PR_AUTHOR=$PR_AUTHOR" >> $GITHUB_ENV
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
      - name: Build and send application stageQa to App Distribution
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          CREDENTIAL_FILE_CONTENT: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          PR_TITLE: ${{ env.PR_TITLE }}
          PR_AUTHOR: ${{ env.PR_AUTHOR }}
          PR_URL: ${{ env.PR_URL }}
        run: |
          echo "$CREDENTIAL_FILE_CONTENT" > ./app/serviceCredentialsFile.json
          echo "App type: stageQa" >> ./app/src/stage/qa/releaseNotes.txt
          echo "buildNumber=${GITHUB_RUN_NUMBER}" >> ./app/src/stage/qa/releaseNotes.txt
          echo "Pull Request Title: $PR_TITLE" >> ./app/src/stage/qa/releaseNotes.txt
          echo "Pull Request Author: $PR_AUTHOR" >> ./app/src/stage/qa/releaseNotes.txt
          echo "Pull Request URL: $PR_URL" >> ./app/src/stage/qa/releaseNotes.txt
          ./gradlew appDistributionToQaStageQa

      - name: Print release notes
        if: success()
        run: |
          echo "Release Notes:"
          cat ./app/src/stage/qa/releaseNotes.txt

      - name: Check status
        run: echo "Check build status and send status"

      - name: Set failed if build failed
        if: failure()
        run: |
          echo "::error::Build or send build stageQa to App Distribution failed"
